In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [79]:
df = pd.read_csv("../../Data/insurance.csv")

In [80]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [81]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
X = df[["age","sex","bmi","children","smoker","region"]]
y = df["charges"]

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 15)

In [85]:
X_train

      age     sex     bmi  children smoker     region
1256   51  female  36.385         3     no  northwest
147    51  female  37.730         1     no  southeast
1042   20    male  30.685         0    yes  northeast
889    57    male  33.630         1     no  northwest
650    49  female  42.680         2     no  southeast
...   ...     ...     ...       ...    ...        ...
1223   20  female  24.420         0    yes  southeast
667    40  female  32.775         2    yes  northwest
156    48    male  24.420         0    yes  southeast
384    44    male  22.135         2     no  northeast
645    48    male  30.780         3     no  northeast

[1070 rows x 6 columns]

In [86]:
X_test

      age     sex    bmi  children smoker     region
38     35    male  36.67         1    yes  northeast
126    19  female  28.30         0    yes  southwest
479    23    male  32.56         0     no  southeast
10     25    male  26.22         0     no  northeast
195    19    male  30.59         0     no  northwest
...   ...     ...    ...       ...    ...        ...
1059   32    male  33.82         1     no  northwest
303    28  female  33.00         2     no  southeast
335    64    male  34.50         0     no  southwest
792    22  female  23.18         0     no  northeast
1213   52  female  33.30         2     no  southwest

[268 rows x 6 columns]

data leakage önlemek için encodingleri şimdi yapıcaz

In [87]:
X_train["sex"] = X_train["sex"].map({"male":0, "female":1})
X_test["sex"] = X_test["sex"].map({"male":0, "female":1})

In [88]:
X_train

      age  sex     bmi  children smoker     region
1256   51    1  36.385         3     no  northwest
147    51    1  37.730         1     no  southeast
1042   20    0  30.685         0    yes  northeast
889    57    0  33.630         1     no  northwest
650    49    1  42.680         2     no  southeast
...   ...  ...     ...       ...    ...        ...
1223   20    1  24.420         0    yes  southeast
667    40    1  32.775         2    yes  northwest
156    48    0  24.420         0    yes  southeast
384    44    0  22.135         2     no  northeast
645    48    0  30.780         3     no  northeast

[1070 rows x 6 columns]

In [89]:
X_train["smoker"] = X_train["smoker"].map({"yes":1, "no":0})
X_test["smoker"] = X_test["smoker"].map({"yes":1, "no":0})

In [90]:
X_train["region"].unique()

<StringArray>
['northwest', 'southeast', 'northeast', 'southwest']
Length: 4, dtype: str

In [91]:
X_train = pd.get_dummies(X_train, columns=["region"], drop_first=True, dtype=int)
X_test = pd.get_dummies(X_test, columns=["region"], drop_first=True, dtype=int)

In [92]:
X_train

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
1256,51,1,36.385,3,0,1,0,0
147,51,1,37.730,1,0,0,1,0
1042,20,0,30.685,0,1,0,0,0
889,57,0,33.630,1,0,1,0,0
650,49,1,42.680,2,0,0,1,0
...,...,...,...,...,...,...,...,...
1223,20,1,24.420,0,1,0,1,0
667,40,1,32.775,2,1,1,0,0
156,48,0,24.420,0,1,0,1,0
384,44,0,22.135,2,0,0,0,0
645,48,0,30.780,3,0,0,0,0

In [93]:
from sklearn.preprocessing import StandardScaler

In [94]:
scaler = StandardScaler()

In [95]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [96]:
X_train

array([[ 0.8143715 ,  1.00938988,  0.92361714, ...,  1.78316783,
        -0.60254238, -0.57375304],
       [ 0.8143715 ,  1.00938988,  1.14285117, ..., -0.56079971,
         1.65963429, -0.57375304],
       [-1.38518087, -0.99069747, -0.00547876, ..., -0.56079971,
        -0.60254238, -0.57375304],
       ...,
       [ 0.60151159, -0.99069747, -1.02666924, ..., -0.56079971,
         1.65963429, -0.57375304],
       [ 0.31769838, -0.99069747, -1.3991226 , ..., -0.56079971,
        -0.60254238, -0.57375304],
       [ 0.60151159, -0.99069747,  0.01000618, ..., -0.56079971,
        -0.60254238, -0.57375304]], shape=(1070, 8))

In [97]:
X_test

array([[-0.32088134, -0.99069747,  0.97007193, ..., -0.56079971,
        -0.60254238, -0.57375304],
       [-1.45613417,  1.00938988, -0.39423204, ..., -0.56079971,
        -0.60254238,  1.74291017],
       [-1.17232096, -0.99069747,  0.30014489, ..., -0.56079971,
         1.65963429, -0.57375304],
       ...,
       [ 1.73676442, -0.99069747,  0.6163635 , ..., -0.56079971,
        -0.60254238,  1.74291017],
       [-1.24327426,  1.00938988, -1.22878835, ..., -0.56079971,
        -0.60254238, -0.57375304],
       [ 0.8853248 ,  1.00938988,  0.42076436, ..., -0.56079971,
        -0.60254238,  1.74291017]], shape=(268, 8))

In [98]:
from sklearn.linear_model import LinearRegression

In [99]:
regression = LinearRegression()

In [100]:
regression.fit(X_train, y_train)

LinearRegression()

In [101]:
y_pred = regression.predict(X_test)

In [102]:
y_pred

array([33890.21746398, 25233.16770791,  3791.35859501,  3236.48950223,
        2753.78589644,  8033.19434312,   986.8359004 , 34996.35894003,
        8442.93273586,  8820.10937347,  3895.51369222,  6211.06335152,
       35977.64400112, 32768.35404822,  5519.16539467, 37357.53637207,
       27197.40132169,  9381.17555737, 30153.99797749,  8237.76932057,
        5443.36483562,  9757.7881789 ,  3380.6687726 , 18562.02604072,
       11847.3988793 ,  8691.27557737,  7683.21386456, 39069.50138105,
        3714.68510187,   -48.3377788 ,  6882.26406994,  9270.97591921,
        5484.24601192, 41119.11931005,  6971.11105692,  5577.71534461,
        5458.22851457,  3827.22533323,  6328.95680314, 11561.51731191,
        7167.25740263, 10780.62087794, 15750.70435474,  2725.46683683,
       11149.61900748, 11239.45478649, 11669.62825239,  6451.20447244,
        9674.10638387, 28654.83352765,  1286.48507399,  2157.91909444,
        9004.72207652, 10266.46054073, 12935.60069719, 26766.68773927,
        1042.92582197, 12366.93775239,  4976.87549627, 15609.85496623,
        6432.66018984, 30690.92700587, 25071.99351563,  5494.8291568 ,
       34375.35533166, 36906.95390492,  4987.18735167, 11001.09821612,
       11498.22536621, 33648.997572  , 10696.95161343,  5159.17983001,
       10882.81204832, 12252.82698181,   -74.40306279,  7523.19616316,
       37076.64733819, 13517.57382483, 19199.49024044,  9831.03924706,
       12733.30097682, 11872.51938623, 39254.48138542,  2360.07422118,
        7897.91466063, 29903.90218548, 16091.98391367,  5084.33934863,
       11796.20846808,  3861.59495746,  5658.42675216,  7110.6167662 ,
        4026.72403665, 10150.08427461,  9872.12552937,  7880.24640478,
        9685.6292385 , 17149.2994744 , 13114.52259322, 12349.08198836,
       11850.43644867,  3313.70553755, 10812.08450588,  7163.52250823,
       14356.22191355, 11796.32831738, 15497.14038511, 32110.50999535,
       11140.8207144 ,  2915.93730933, 26855.94485018, 27450.02118569,
        3802.07654262, 11815.15811024,  6189.7413685 ,  5432.00889989,
        4219.01715873,  3372.79965303,  4275.78156099, 35423.14361815,
       11096.16251254, 12619.50772665,  3714.7262359 ,  8708.45648739,
       10682.25164197, 29203.90694385,  4326.76786334, 10609.0606724 ,
       35189.89532808, 10890.2508201 , 11766.6998043 ,  5789.23713559,
       12825.2995698 , 13357.90545762, 14757.31660358, 10173.22088817,
        -230.06246845, 15150.70473478,  6510.27988688,  7936.87928263,
       34093.41513111, 10488.35870773,  5129.30648814,  2124.12820356,
       11296.25347493,  9080.84056494,  7875.75814548, 10050.00501444,
       17025.67276372,  6942.26822415,  9440.52648992,  5432.39087286,
       39618.79416081,  9506.19191092, 13497.41346522, 11736.7837431 ,
        8238.87163185, 10257.75182174, 12718.98261015,   581.57601411,
       12891.28227189, 10874.58228005,  4643.53438268,  6934.76189442,
       32072.21109833, 11246.58748486,  4116.46006025,  5605.43250397,
       33486.61662749, 27516.47835423,  9557.99224143, 14547.48320169,
       30666.1181898 , 27333.50829551, -1557.04554499,  9387.5202558 ,
       28793.76299714, 10701.27239043, 34017.33667076, 11356.46147586,
       35365.04685117, 13465.4615886 ,  7743.03926356, 14752.90349929,
         338.3754573 ,  5096.7521231 ,  6974.88463339, 32191.49336863,
        8872.03579179,  4496.29108226, 16018.83162617, 10065.20474352,
       10358.16116573,  3695.90929337, 10318.51582452, 34688.71084952,
        4245.61523206, 25097.36299465,  9455.49560697,  7186.97846351,
        5826.49613885,  3116.42805463, 14443.97685948, 36890.99474137,
       10559.33766465,  6968.49097712,  9623.76901334, 31554.24072828,
       12147.92770483,  5808.76022411,  8940.41491721,  3604.98776298,
        8322.28210893, 33976.24546689,  7146.59297191, 11120.94259462,
        7443.71615124,   170.55341661, 11130.65254977,  2229.45468217,
        9250.59897371, 13382.87194064,  8551.76002605,  3982.10759777,
       11533.95957501,  1651.55414558,  6591.61319965, 35610.23223324,
       30847.47055161, 27774.49829323,  8842.81974175,  7650.60148471,
        7691.36067058,  1659.92250497,   728.78351785,  1254.23145459,
        4009.17090651, 32092.0577309 , 23701.30214795, -1939.08118955,
       27152.43942356, 24078.38986658,  5827.23214595,  5331.35503003,
       13030.93565926,  2131.99732312,   306.12183791,  4876.55895103,
       15288.6251924 ,  9125.93247529,  9531.80652512, 17388.60257606,
        2005.70850919, 11468.97342353, 26347.00076031,  6363.60588952,
       30558.71239817, 11682.39991729,  4017.0343706 ,  2258.60166207,
        5760.0521219 , 38859.00286351, 14125.68026353,  7863.14472782,
        6422.4486313 , 15290.04721358,  1375.95025897, 12910.95817105])

In [103]:
from sklearn.metrics import r2_score

In [104]:
r2_score(y_test, y_pred)

0.7709928565663493