In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../../Data/used_phone_price_prediction_1M.csv")

In [3]:
df.head()

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,...,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,market_demand_score,resale_price
0,Realme,Realme GT,2025,4,256,6.93,4130,47,100,Android,...,0,0,0,Tier1,Individual,11,1,1,99,47891.46
1,Samsung,Galaxy S21,2024,16,64,6.29,5558,81,67,Android,...,0,0,0,Tier3,Store,8,1,0,64,17663.21
2,Apple,iPhone 11,2022,4,128,5.52,5945,59,67,iOS,...,0,0,0,Tier1,Individual,0,0,1,68,67268.20
3,Google,Pixel 6,2024,16,512,5.99,5767,84,57,Android,...,0,0,1,Tier1,Store,11,1,1,50,12626.26
4,Google,Pixel 7,2021,4,128,6.59,5336,98,44,Android,...,0,0,0,Tier3,Store,24,1,1,66,20662.25

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 28 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   brand                      1000000 non-null  str
 1   model                      1000000 non-null  str
 2   release_year               1000000 non-null  int64
 3   ram_gb                     1000000 non-null  int64
 4   storage_gb                 1000000 non-null  int64
 5   screen_size_inches         1000000 non-null  float64
 6   battery_capacity           1000000 non-null  int64
 7   processor_score            1000000 non-null  int64
 8   camera_score               1000000 non-null  int64
 9   os_type                    1000000 non-null  str
 10  has_5g                     1000000 non-null  int64
 11  original_price             1000000 non-null  int64
 12  purchase_year              1000000 non-null  int64
 13  age_months                 1000000 non-null  int64
 14  usage_hours_per_day        1000000 non-null  float64
 15  condition                  1000000 non-null  str
 16  battery_health             1000000 non-null  int64
 17  screen_cracked             1000000 non-null  int64
 18  body_damage                1000000 non-null  int64
 19  repair_history             1000000 non-null  int64
 20  water_damage               1000000 non-null  int64
 21  city_tier                  1000000 non-null  str
 22  seller_type                1000000 non-null  str
 23  warranty_remaining_months  1000000 non-null  int64
 24  box_available              1000000 non-null  int64
 25  charger_available          1000000 non-null  int64
 26  market_demand_score        1000000 non-null  int64
 27  resale_price               1000000 non-null  float64
dtypes: float64(3), int64(19), str(6)
memory usage: 213.6 MB

In [5]:
df.describe()

,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,has_5g,original_price,purchase_year,...,battery_health,screen_cracked,body_damage,repair_history,water_damage,warranty_remaining_months,box_available,charger_available,market_demand_score,resale_price
count,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,2022.001836,9.201878,396.798912,6.25037,4750.004425,70.018905,69.980058,0.800063,79966.195735,2023.501257,...,77.507898,0.079978,0.119653,0.15053,0.030106,8.099701,0.699651,0.849771,70.020885,22597.996211
std,2.001558,4.309755,349.401760,0.43290,1009.971322,17.600272,17.607651,0.399953,40413.479880,1.607323,...,13.272198,0.271259,0.324555,0.35759,0.170879,8.158009,0.458410,0.357296,17.618549,16652.621181
min,2019.000000,4.000000,64.000000,5.50000,3000.000000,40.000000,40.000000,0.000000,10000.000000,2019.000000,...,55.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,40.000000,2000.000000
25%,2020.000000,6.000000,128.000000,5.88000,3877.000000,55.000000,55.000000,1.000000,45028.000000,2023.000000,...,66.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,55.000000,10365.927500
50%,2022.000000,8.000000,256.000000,6.25000,4750.000000,70.000000,70.000000,1.000000,79947.000000,2024.000000,...,78.000000,0.000000,0.000000,0.00000,0.000000,6.000000,1.000000,1.000000,70.000000,18555.195000
75%,2024.000000,12.000000,512.000000,6.63000,5623.000000,85.000000,85.000000,1.000000,114984.000000,2025.000000,...,89.000000,0.000000,0.000000,0.00000,0.000000,15.000000,1.000000,1.000000,85.000000,30427.912500
max,2025.000000,16.000000,1024.000000,7.00000,6500.000000,100.000000,100.000000,1.000000,150000.000000,2025.000000,...,100.000000,1.000000,1.000000,1.00000,1.000000,24.000000,1.000000,1.000000,100.000000,160257.480000

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 15)

In [9]:
X_train.head()

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,market_demand_score
737249,Vivo,Vivo V27,2019,12,512,6.27,3940,98,65,Android,...,0,0,0,0,Tier3,Store,0,1,1,62
228182,OnePlus,OnePlus 10,2024,16,64,6.36,3744,82,49,Android,...,0,0,0,0,Tier2,Individual,0,1,1,79
495703,Vivo,Vivo X90,2019,12,64,6.37,4945,64,80,Android,...,0,0,0,0,Tier1,Individual,0,1,0,98
205931,Vivo,Vivo X90,2021,6,256,5.91,5551,57,56,Android,...,0,0,1,0,Tier2,Store,0,0,1,83
539955,OnePlus,OnePlus 11,2022,12,128,5.76,4698,49,71,Android,...,0,0,1,0,Tier1,Store,13,0,0,90

In [10]:
X_train = pd.get_dummies(X_train, columns=["brand"], drop_first=True, dtype=int)
X_test = pd.get_dummies(X_test, columns=["brand"], drop_first=True, dtype=int)

In [11]:
X_train.head()

,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,has_5g,...,warranty_remaining_months,box_available,charger_available,market_demand_score,brand_Google,brand_OnePlus,brand_Realme,brand_Samsung,brand_Vivo,brand_Xiaomi
737249,Vivo V27,2019,12,512,6.27,3940,98,65,Android,0,...,0,1,1,62,0,0,0,0,1,0
228182,OnePlus 10,2024,16,64,6.36,3744,82,49,Android,1,...,0,1,1,79,0,1,0,0,0,0
495703,Vivo X90,2019,12,64,6.37,4945,64,80,Android,1,...,0,1,0,98,0,0,0,0,1,0
205931,Vivo X90,2021,6,256,5.91,5551,57,56,Android,0,...,0,0,1,83,0,0,0,0,1,0
539955,OnePlus 11,2022,12,128,5.76,4698,49,71,Android,1,...,13,0,0,90,0,1,0,0,0,0

In [12]:
model_price_map = y_train.groupby(X_train["model"]).mean()
X_train["model_target_enc"] = X_train["model"].map(model_price_map)
X_test["model_target_enc"] = X_test["model"].map(model_price_map)

In [13]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[["Tier3", "Tier2", "Tier1"]])
X_train["city_tier_encoded"] = oe.fit_transform(X_train[["city_tier"]])

oe = OrdinalEncoder(categories=[["Tier3", "Tier2", "Tier1"]])
X_test["city_tier_encoded"] = oe.fit_transform(X_test[["city_tier"]])

In [14]:
oe = OrdinalEncoder(categories=[["Poor","Fair","Good","Excellent"]])
X_train["condition_tier"] = oe.fit_transform(X_train[["condition"]])

oe = OrdinalEncoder(categories=[["Poor","Fair","Good","Excellent"]])
X_test["condition_tier"] = oe.fit_transform(X_test[["condition"]])

In [15]:
X_train

,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,has_5g,...,market_demand_score,brand_Google,brand_OnePlus,brand_Realme,brand_Samsung,brand_Vivo,brand_Xiaomi,model_target_enc,city_tier_encoded,condition_tier
737249,Vivo V27,2019,12,512,6.27,3940,98,65,Android,0,...,62,0,0,0,0,1,0,20325.568233,0.0,1.0
228182,OnePlus 10,2024,16,64,6.36,3744,82,49,Android,1,...,79,0,1,0,0,0,0,22397.805694,1.0,0.0
495703,Vivo X90,2019,12,64,6.37,4945,64,80,Android,1,...,98,0,0,0,0,1,0,20261.870960,2.0,2.0
205931,Vivo X90,2021,6,256,5.91,5551,57,56,Android,0,...,83,0,0,0,0,1,0,20261.870960,1.0,2.0
539955,OnePlus 11,2022,12,128,5.76,4698,49,71,Android,1,...,90,0,1,0,0,0,0,22384.057785,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704375,Pixel 6,2024,16,1024,6.12,5821,57,80,Android,1,...,43,1,0,0,0,0,0,23548.844604,1.0,2.0
199301,OnePlus 9,2019,8,128,5.78,4040,75,78,Android,1,...,48,0,1,0,0,0,0,22386.999789,0.0,1.0
794508,OnePlus 10,2020,6,1024,6.01,6080,92,41,Android,1,...,42,0,1,0,0,0,0,22397.805694,2.0,3.0
446197,Vivo X90,2020,16,64,5.64,3044,58,98,Android,1,...,44,0,0,0,0,1,0,20261.870960,1.0,3.0
794056,Pixel 7,2024,6,128,6.25,4034,47,45,Android,0,...,85,1,0,0,0,0,0,23753.923457,0.0,1.0

In [16]:
X_train = pd.get_dummies(X_train, columns=["os_type"], drop_first=True, dtype=int)
X_test = pd.get_dummies(X_test, columns=["os_type"], drop_first=True, dtype=int)

In [17]:
X_train

,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,has_5g,original_price,...,brand_Google,brand_OnePlus,brand_Realme,brand_Samsung,brand_Vivo,brand_Xiaomi,model_target_enc,city_tier_encoded,condition_tier,os_type_iOS
737249,Vivo V27,2019,12,512,6.27,3940,98,65,0,140541,...,0,0,0,0,1,0,20325.568233,0.0,1.0,0
228182,OnePlus 10,2024,16,64,6.36,3744,82,49,1,10279,...,0,1,0,0,0,0,22397.805694,1.0,0.0,0
495703,Vivo X90,2019,12,64,6.37,4945,64,80,1,39766,...,0,0,0,0,1,0,20261.870960,2.0,2.0,0
205931,Vivo X90,2021,6,256,5.91,5551,57,56,0,43894,...,0,0,0,0,1,0,20261.870960,1.0,2.0,0
539955,OnePlus 11,2022,12,128,5.76,4698,49,71,1,22453,...,0,1,0,0,0,0,22384.057785,2.0,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704375,Pixel 6,2024,16,1024,6.12,5821,57,80,1,10908,...,1,0,0,0,0,0,23548.844604,1.0,2.0,0
199301,OnePlus 9,2019,8,128,5.78,4040,75,78,1,91779,...,0,1,0,0,0,0,22386.999789,0.0,1.0,0
794508,OnePlus 10,2020,6,1024,6.01,6080,92,41,1,60268,...,0,1,0,0,0,0,22397.805694,2.0,3.0,0
446197,Vivo X90,2020,16,64,5.64,3044,58,98,1,42050,...,0,0,0,0,1,0,20261.870960,1.0,3.0,0
794056,Pixel 7,2024,6,128,6.25,4034,47,45,0,139835,...,1,0,0,0,0,0,23753.923457,0.0,1.0,0

In [18]:
X_train = pd.get_dummies(X_train, columns=["seller_type"], drop_first=True, dtype=int)
X_test = pd.get_dummies(X_test, columns=["seller_type"], drop_first=True, dtype=int)

In [19]:
X_train

,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,has_5g,original_price,...,brand_OnePlus,brand_Realme,brand_Samsung,brand_Vivo,brand_Xiaomi,model_target_enc,city_tier_encoded,condition_tier,os_type_iOS,seller_type_Store
737249,Vivo V27,2019,12,512,6.27,3940,98,65,0,140541,...,0,0,0,1,0,20325.568233,0.0,1.0,0,1
228182,OnePlus 10,2024,16,64,6.36,3744,82,49,1,10279,...,1,0,0,0,0,22397.805694,1.0,0.0,0,0
495703,Vivo X90,2019,12,64,6.37,4945,64,80,1,39766,...,0,0,0,1,0,20261.870960,2.0,2.0,0,0
205931,Vivo X90,2021,6,256,5.91,5551,57,56,0,43894,...,0,0,0,1,0,20261.870960,1.0,2.0,0,1
539955,OnePlus 11,2022,12,128,5.76,4698,49,71,1,22453,...,1,0,0,0,0,22384.057785,2.0,2.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704375,Pixel 6,2024,16,1024,6.12,5821,57,80,1,10908,...,0,0,0,0,0,23548.844604,1.0,2.0,0,0
199301,OnePlus 9,2019,8,128,5.78,4040,75,78,1,91779,...,1,0,0,0,0,22386.999789,0.0,1.0,0,1
794508,OnePlus 10,2020,6,1024,6.01,6080,92,41,1,60268,...,1,0,0,0,0,22397.805694,2.0,3.0,0,0
446197,Vivo X90,2020,16,64,5.64,3044,58,98,1,42050,...,0,0,0,1,0,20261.870960,1.0,3.0,0,0
794056,Pixel 7,2024,6,128,6.25,4034,47,45,0,139835,...,0,0,0,0,0,23753.923457,0.0,1.0,0,0

In [21]:
X_train.drop(columns=["model","condition","city_tier"], inplace=True)

In [22]:
X_test.drop(columns=["model","condition","city_tier"], inplace=True)

In [23]:
X_train

,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,has_5g,original_price,purchase_year,...,brand_OnePlus,brand_Realme,brand_Samsung,brand_Vivo,brand_Xiaomi,model_target_enc,city_tier_encoded,condition_tier,os_type_iOS,seller_type_Store
737249,2019,12,512,6.27,3940,98,65,0,140541,2024,...,0,0,0,1,0,20325.568233,0.0,1.0,0,1
228182,2024,16,64,6.36,3744,82,49,1,10279,2025,...,1,0,0,0,0,22397.805694,1.0,0.0,0,0
495703,2019,12,64,6.37,4945,64,80,1,39766,2022,...,0,0,0,1,0,20261.870960,2.0,2.0,0,0
205931,2021,6,256,5.91,5551,57,56,0,43894,2023,...,0,0,0,1,0,20261.870960,1.0,2.0,0,1
539955,2022,12,128,5.76,4698,49,71,1,22453,2023,...,1,0,0,0,0,22384.057785,2.0,2.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704375,2024,16,1024,6.12,5821,57,80,1,10908,2025,...,0,0,0,0,0,23548.844604,1.0,2.0,0,0
199301,2019,8,128,5.78,4040,75,78,1,91779,2024,...,1,0,0,0,0,22386.999789,0.0,1.0,0,1
794508,2020,6,1024,6.01,6080,92,41,1,60268,2024,...,1,0,0,0,0,22397.805694,2.0,3.0,0,0
446197,2020,16,64,5.64,3044,58,98,1,42050,2020,...,0,0,0,1,0,20261.870960,1.0,3.0,0,0
794056,2024,6,128,6.25,4034,47,45,0,139835,2024,...,0,0,0,0,0,23753.923457,0.0,1.0,0,0

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler = StandardScaler()

In [26]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
from sklearn.linear_model import LinearRegression

In [29]:
regression = LinearRegression()

In [30]:
regression.fit(X_train, y_train)

LinearRegression()

In [31]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [32]:
y_pred = regression.predict(X_test)

In [33]:
mae = mean_absolute_error(y_test, regression.predict(X_test))
mse = mean_squared_error(y_test, regression.predict(X_test))
r2 = r2_score(y_test, regression.predict(X_test))

In [34]:
print(mae)
print(mse)
print(r2)

4836.734034425284
46968248.971450716
0.8310024806130119